apiVersion: v1
kind: ConfigMap
metadata:
  name: hassio-secrets-template
  namespace: homeassistant
data:
  secrets-template.yaml: |
    database_url: "${DATABASE_URL}"
    client_secret: "${CLIENT_SECRET}"
    client_id: "${CLIENT_ID}"
