apiVersion: apps/v1
kind: Deployment
metadata:
  name: drop
  namespace: entertainment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: drop
  template:
    metadata:
      labels:
        app: drop
    spec:
      volumes:
        - name: drop-storage
          persistentVolumeClaim:
            claimName: drop-storage-pvc
        - name: entertainment-content
          persistentVolumeClaim:
            claimName: entertainment-content-pvc
      containers:
        - name: drop
          image: ghcr.io/drop-oss/drop:v0.3.4
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: drop-config
            - secretRef:
                name: drop-secrets
          volumeMounts:
            - name: drop-storage
              mountPath: /data
            - name: entertainment-content
              mountPath: /library
              subPath: media/games
          startupProbe:
            httpGet:
              path: /api/v1/
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /api/v1/
              port: http
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /api/v1/
              port: http
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 10
