apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: drop-secrets-infisical
  namespace: entertainment
spec:
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: cluster-secrets-rgq1
        envSlug: dev
        secretsPath: /drop
        recursive: true
      credentialsRef:
        secretName: infisical-machine-id
        secretNamespace: infisical
  managedSecretReference:
    secretName: drop-secrets
    secretNamespace: entertainment
    creationPolicy: Owner
