apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drop
  namespace: entertainment
  labels:
    name: drop
spec:
  rules:
    - host: drop.zefirsroyal.cloud
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: drop
                port:
                  number: 3000
