apiVersion: v1
kind: Service
metadata:
  name: drop
  namespace: entertainment
  labels:
    app: drop
spec:
  selector:
    app: drop
  ports:
    - port: 3000
      targetPort: 3000
      name: http
      protocol: TCP
  type: ClusterIP
